name: Deploy to FTP 🚀

on:
  push:
    branches:
      - dev 

jobs:
  deploy:
    name: Deploy via FTP 🚀
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository ✅
        uses: actions/checkout@v4

      - name: Deploy to FTP Server 🚀
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.tgsoftware.services
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: ./flavorflow/
          protocol: ftp   