name: Deploy to FTP 🚀

on:
  push:
    branches:
<<<<<<< HEAD
      - prod  
=======
      - production  
>>>>>>> 8b9547f878e1fc25a0a220828308d0c68b6072b9

jobs:
  deploy:
    name: Deploy via FTP 🚀
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository ✅
        uses: actions/checkout@v4

      - name: Deploy to FTP Server 🚀
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.tgsoftware.services
          username: velisoft@velisoft.tgsoftware.services
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          local-dir: ./
<<<<<<< HEAD
          server-dir: ./flavorflow
=======
          server-dir: ./flavorflow/
>>>>>>> 8b9547f878e1fc25a0a220828308d0c68b6072b9
