name: Deploy to FTP 🚀

on:
  push:
    branches:
      - production  

jobs:
  deploy:
    name: Deploy via FTP 🚀
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository ✅
        uses: actions/checkout@v4

      - name: Deploy to FTP Server 🚀
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ftp.tgsoftware.services
          username: velisoft@velisoft.tgsoftware.services
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          local-dir: ./
          server-dir: ./flavorflow/